version: '3.7'
services:
  backend:
    image: be-tiendavideo-img
    container_name: be-tiendavideo-con
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://postgres:5432/TiendaVideo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1407
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: bd-tiendavideo-con
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=TiendaVideo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1407
